### ISSUE TITLE
Is this lib Angular 8 or 9 compatible?

### ISSUE THREAD

**Issue by sh977218** [ABenassi87/ngx-text-diff#41]

**Comment by govindthakur25** [comment]
@sh977218 not yet. There is a [PR](https://github.com/ABenassi87/ngx-text-diff/pull/32) for the same which is awaiting reviewal.

**Comment by 31piy** [comment]
@sh977218 I've been using it with Angular 8 for a while, and it seems working fine.

**Comment by sh977218** [comment]
@31piy  Yeah, angular 8 is fine, but not angular 9.

**Comment by ABenassi87** [comment]
Hi @sh977218, thanks for your question and apologize for the delay to answer that. FYI, yesterday I released the version `0.6.0` that supports angular 9.
